name             'ntppool_deployment'
maintainer       'Andy Boutte'
maintainer_email 'andyboutte@gmail.com'
license          'All rights reserved'
description      'Installs/Configures ntppool_deployment'
long_description 'Installs/Configures ntppool_deployment'
version          '0.1.0'

depends 'ntp', '~> 3.3.1'
depends 'chef_hostname', '~> 0.4.2'
depends 'magic_shell', '~> 1.0.0'
