name             'ntppool_deployment'
maintainer       'Andy Boutte'
maintainer_email 'andyboutte@mac.com'
license          'All rights reserved'
description      'Installs/Configures ntppool_deployment'
long_description 'Installs/Configures ntppool_deployment'
version          '0.1.0'

depends 'chef_hostname'
depends 'sudo'
